set nocompatible              
set number
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Functionality Plugins.
Plugin 'VundleVim/Vundle.vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'eiginn/netrw'
" Syntax Plugins.
Plugin 'saltstack/salt-vim'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'hashivim/vim-vagrant'

call vundle#end()
let g:netrw_liststyle=3
let g:netrw_keepdir=0
color elfpriest
filetype plugin indent on
syntax on

au BufRead,BufNewFile *.cf set filetype=pfmain
au BufRead,BufNewFile *sshd_config* set filetype=sshdconfig
