set nocompatible              
set number
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'saltstack/salt-vim'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'hashivim/vim-vagrant'

call vundle#end()
let g:netrw_liststyle=3
color elflord
filetype plugin indent on
syntax on

au BufRead,BufNewFile *.cf set filetype=pfmain
