gui:
  skipDiscardChangeWarning: true
  commitHashLength: 4
  showDivergenceFromBaseBranch: arrowAndNumber
  commitAuthorShortLength: 2
  spinner:
    frames:
      - "\uee06"
      - "\uee07"
      - "\uee08"
      - "\uee09"
      - "\uee0A"
      - "\uee0B"
git:
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --paging=never
update:
  method: background
  days: 1
refresher:
  refreshInterval: 600
  fetchInterval: 3600
customCommands:
  - key: "G"
    context: "localBranches"
    command: "git gone"
    description: "Remove local branches that have been removed on remote"
