export XDG_CONFIG_HOME="$HOME/.config"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
	aws
	chruby
	docker
	docker-compose
	fzf
	git
	git-prompt
	gitfast
	helm
	kubectl
	minikube
	pyenv
	ripgrep
	you-should-use
	zsh-autosuggestions
	zsh-bat
	zsh-syntax-highlighting
)

alias vim="nvim"

# Update Settings
zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 7

eval "$(pyenv init --path)"
eval "$(zoxide init zsh)"
