export XDG_CONFIG_HOME="$HOME/.config"

# LazyGit Configuration
export LG_CONFIG_FILE="$XDG_CONFIG_HOME/lazygit/config.yml,$HOME/.local/share/nvim/lazy/tokyonight.nvim/extras/lazygit/tokyonight_moon.yml"

# eza Configuration
export EZA_ICONS_AUTO="auto"

FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  aws
  docker
  docker-compose
  fzf
  git
  git-prompt
  gitfast
  helm
  kubectl
  minikube
  pyenv
  rbenv
  you-should-use
  zsh-autosuggestions
  zsh-bat
  zsh-syntax-highlighting
)

alias vim="nvim"

# Update Frequency Settings
zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 7

# ZSH Completion Settings
LISTMAX=200

eval "$(pyenv init --path)"
eval "$(zoxide init zsh)"
