ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
	aws
	chruby
	fzf
	git
	git-prompt
	gitfast
	helm
	kubectl
	minikube
	pyenv
	ripgrep
)

# Update Settings
zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 7

eval "$(pyenv init --path)"
eval "$(zoxide init zsh)"
